### ISSUE TITLE
Where is the code

### ISSUE THREAD

**Issue by Kek5chen** [Niimphu/push_swap_visualiser#1]
![image](https://github.com/Niimphu/push_swap_visualiser/assets/52585984/c91741a1-c872-4639-bb86-fd70dc0c0077)

**Comment by Niimphu** [comment]
Another repo linked in the readme 😌

**Comment by Kek5chen** [comment]
Damn, why? Just make a release with the binary and put the code where it belongs.

**Comment by Niimphu** [comment]
Just didn't care enough to work it out, if it works it works 👍

**Comment by Kek5chen** [comment]
Truth
